name: push-workflow 1
on: push

jobs:
  push-job:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: echo Hello world
    - name: step2
      run: |
        echo "Hello world"
        echo "github actions"
