name: workflow-dispatch

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'set name'
        required: true
        default: 'github actions'
        type: string
      environment:
        description: 'set environment'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - qa
          - production

jobs:
  workflow-dispatch-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "Hello, ${{ inputs.name }}!"
      - name: step2
        run: |
          echo hello world
      - name: echo inputs
        run: |
          echo "name: ${{ inputs.name }}"
          echo "environment: ${{ inputs.environment }}"
  