name: create-repo
on:
  workflow_dispatch:
    inputs:
      prefix:
        description: "Prefix for the repository name"
        required: true
        default: "service"
        type: choice
        options:
          - service
          - app
      name:
        description: "Name for the repository"
        required: true
        default: "test"
        type: string

jobs:
  create-repo-automation:
    runs-on: ubuntu-latest
    steps:
    - name: gh auth login
      run: |
        echo ${{ secrets.PERSONAL_ACCESS_TOKEN }} | gh auth login --with-token
    - name: create-repo
      id: create-repo
      run: |
        gh repo create tokkaiiiactions/${{ inputs.prefix }}-${{ inputs.name }} --public --add-readme
    - name: slack 
      if: always()
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "attachments": [
              {
                "pretext": "create repo result",
                "color": "28a745",
                "fields": [
                  {
                    "title": "create repo result ${{ steps.create-repo.outcome }}",
                    "short": true,
                    "value": "${{ inputs.prefix }}-${{ inputs.name }}"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK