name: environment
on:
  push

jobs:
  get-env:
    runs-on: ubuntu-latest
    steps:
      - name: check env & secret
        run: |
          echo ${{ env.level }}
          echo ${{ secrets.key }}
  